project/flask_dashboard/app/base/models.py
"""# -*- encoding: utf-8 -*-

Copyright (c) 2019 - present AppSeed.us
"""

"""from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None"""

project/flask_dashboard/app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

project/flask_dashboard/app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

project/flask_dashboard/app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from flask_dashboard.app import login_manager
from flask_dashboard.app.base import blueprint
from flask_dashboard.app.base.forms import LoginForm, CreateAccountForm
#from app.base.models import User
from models import SuperUser
from flask_dashboard.app.base.util import verify_user

#from flask_dashboard.app.base.util import verify_pass

@login_manager.user_loader
def user_loader(user_id):
    return SuperUser.get(user_id)

@login_manager.request_loader
def request_loader(request):
    user_id = request.form.get('user_id')
    user = SuperUser.get_or_none(SuperUser.user_id == user_id)
    return user if user else None

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if len(request.args) > 0 :
        tg_data = {
            "id" : request.args.get('id',None),
            "first_name" : request.args.get('first_name',None),
            "last_name" : request.args.get('last_name', None),
            "username" : request.args.get('username', None),
            "photo_url" : request.args.get('photo_url',None),
            "auth_date":  request.args.get('auth_date', None),
            "hash" : request.args.get('hash',None)
        }
        print(tg_data)
        res = verify_user(tg_data)
        print(res)
        if res:
            user = SuperUser.get_or_none(SuperUser.user_id == tg_data["id"])
            if user is not None:
                if tg_data["photo_url"] is not None:
                    if user.icon != tg_data["photo_url"]:
                        user.icon = tg_data["photo_url"]
                        user.save()
                login_user(user)
                return redirect(url_for('base_blueprint.route_default'))
            else:
                return render_template( 'accounts/login.html', msg='Отказано в доступе, Вы не администратор')
        else:
            return render_template( 'accounts/login.html', msg='Неверные параметры')
    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html')
    return redirect(url_for('app_main.main'))


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    #return render_template('page-403.html'), 403
    return redirect(url_for('base_blueprint.login'))

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    print("Скакнули сюда")
    return render_template('page-500.html'), 500

project/flask_dashboard/app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    Вход
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Войдите через Telegram аккаунт
                                    {% endif %}                                     
                                </p>    
                            </div>
                            <div class="col-md-6 col-md-offset-3" style="margin: 0 auto">
                                <script async src="https://telegram.org/js/telegram-widget.js?14" data-telegram-login="registration_testbot" data-size="large" data-auth-url="/login" data-request-access="write"></script>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/flask_dashboard/app/base/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a target="_blank"
                                       href="https://appseed.us/admin-dashboards/flask-dashboard-volt">Flask Volt</a> - Sign UP
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p>    
                            </div>
                            
                            <form method="post" action="">
                            
                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-user-shield"></span></span>
                                        {{ form.username(placeholder="Username", class="form-control") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Your Email</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                        {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->

                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                                            <label class="form-check-label" for="defaultCheck5">
                                              Agree terms
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <a href="{{ url_for('base_blueprint.login') }}" class="small text-right">Login</a>
                                        </div>
                                    </div>
                                    
                                </div>
                                <button type="submit" name="register" class="btn btn-block btn-primary">Sign in</button>
                            </form>
                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="font-weight-normal">
                                    &copy; <a  href="https://themesberg.com" target="_blank">Themesberg</a> 
                                    - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/flask_dashboard/app/base/templates/includes/footer.html
    <footer class="footer section py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-6 mb-4 mb-lg-0">
                    <p class="mb-0 text-center text-xl-left">
                        &copy; <a class="text-primary font-weight-normal" href="https://themesberg.com" target="_blank">Themesberg</a>
                        - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
                    </p>
                </div>

                <div class="col-12 col-lg-6">
                    <!-- List -->
                    <ul class="list-inline list-group-flush list-group-borderless text-center text-xl-right mb-0">
                        <li class="list-inline-item px-0 px-sm-2">
                            <a target="_blank" 
                               href="https://appseed.us/admin-dashboards/flask-dashboard-volt">Flask Volt Dashboard</a>
                        </li>
                    </ul>
                    <!-- End List -->
                </div>
            </div>
        </div>
    </footer>

project/flask_dashboard/app/base/templates/includes/navigation.html
        <nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark pl-0 pr-2 pb-0">
            <div class="container-fluid px-0">
              <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                <div class="d-flex">
                </div>
                <!-- Navbar links -->
                <ul class="navbar-nav align-items-center">
                  <li class="nav-item dropdown">
                    <a class="nav-link text-dark mr-lg-3 icon-notifications" data-unread-notifications="true" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="icon icon-sm">
                        <span class="fas fa-bell bell-shake"></span>
                        <span class="icon-badge rounded-circle unread-notifications"></span>
                      </span>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                      <div class="list-group list-group-flush">
                        <a href="#" class="text-center text-primary font-weight-bold border-bottom border-light py-3">Notifications</a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-1.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Jose Leos</h4>
                                    </div>
                                    <div class="text-right">
                                      <small class="text-danger">a few moments ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">Added you to an event "Project stand-up" tomorrow at 12:30 AM.</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-2.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Neil Sims</h4>
                                    </div>
                                    <div class="text-right">
                                      <small class="text-danger">2 hrs ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">You've been assigned a task for "Awesome new project".</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Roberta Casas</h4>
                                    </div>
                                    <div class="text-right">
                                      <small>5 hrs ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">Tagged you in a document called "First quarter financial plans",</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-4.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Joseph Garth</h4>
                                    </div>
                                    <div class="text-right">
                                      <small>1 d ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">New message: "Hey, what's up? All set for the presentation?"</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                          <div class="row align-items-center">
                              <div class="col-auto">
                                <!-- Avatar -->
                                <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-5.jpg" class="user-avatar lg-avatar rounded-circle">
                              </div>
                              <div class="col pl-0 ml--2">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                      <h4 class="h6 mb-0 text-small">Bonnie Green</h4>
                                    </div>
                                    <div class="text-right">
                                      <small>2 hrs ago</small>
                                    </div>
                                </div>
                                <p class="font-small mt-1 mb-0">New message: "We need to improve the UI/UX for the landing page."</p>
                              </div>
                          </div>
                        </a>
                        <a href="#" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
                      </div>
                    </div>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link pt-1 px-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <div class="media d-flex align-items-center">
                        <img class="user-avatar md-avatar rounded-circle" alt="Image placeholder" src="{{current_user.icon}}">
                        <div class="media-body ml-2 text-dark align-items-center d-none d-lg-block">
                          <span class="mb-0 font-small font-weight-bold">
                            {{ current_user.full_name }}
                          </span>
                        </div>
                      </div>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-right mt-2">
                      <a class="dropdown-item font-weight-bold" href="/settings.html"><span class="fas fa-cog"></span>Settings</a>
                      <div role="separator" class="dropdown-divider"></div>
                      <a class="dropdown-item font-weight-bold" href="{{ url_for('base_blueprint.logout') }}">
                          <span class="fas fa-sign-out-alt text-danger"></span>Logout</a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
        </nav>

project/flask_dashboard/app/base/templates/includes/scripts.html
    <!-- Core -->
    <script src="/static/assets/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    
    <!-- Vendor JS -->
    <script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>
    
    <!-- Slider -->
    <script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>
    
    <!-- Jarallax -->
    <script src="/static/assets/vendor/jarallax/dist/jarallax.min.js"></script>
    
    <!-- Smooth scroll -->
    <script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    
    <!-- Count up -->
    <script src="/static/assets/vendor/countup.js/dist/countUp.umd.js"></script>
    
    <!-- Notyf -->
    <script src="/static/assets/vendor/notyf/notyf.min.js"></script>
    
    <!-- Charts -->
    <script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
    <script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    
    <!-- Datepicker -->
    <script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>
    
    <!-- Simplebar -->
    <script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- Volt JS -->
    <script src="/static/assets/js/volt.js"></script>

project/flask_dashboard/app/base/templates/includes/sidebar.html
    <nav id="sidebarMenu" class="sidebar d-md-block bg-primary text-white collapse px-4">
        <div class="sidebar-sticky pt-3 mx-auto">
            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="user-avatar lg-avatar mr-4">
                <img src="/static/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white" alt="Bonnie Green">
                </div>
                <div class="d-block">
                <h2 class="h6">
                    {{ current_user.full_name }}
                </h2>
                <a href="{{ url_for('base_blueprint.logout') }}" class="btn btn-secondary text-dark btn-xs">
                    <span class="mr-2"><span class="fas fa-sign-out-alt"></span></span>Выход</a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" class="fas fa-times" data-toggle="collapse"
                    data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation"></a>
            </div>
            </div>
            <ul class="nav flex-column">
            <li class="nav-item  {% if 'dashboard' in segment %} active {% endif %}">
                <a href="/dashboard" class="nav-link">
                <span class="sidebar-icon"><span class="fas fa-chart-pie"></span></span>
                <span>Главная</span>
                </a>
            </li>
            <li class="nav-item  {% if 'transactions' in segment %} active {% endif %}">
                <a href="/transactions" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-hand-holding-usd"></span></span>
                    <span>Заказы</span>
                </a>
            </li>
            <li class="nav-item  {% if 'products' in segment %} active {% endif %}">
                <a href="/products" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-box-open"></span></span> 
                    Товары
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'categories' in segment %} active {% endif %}">
                <a href="/categories" class="nav-link">
                    <span class="sidebar-icon"><span class="fa fa-list-alt"></span></span> 
                    Категории
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'subcategories' in segment %} active {% endif %}">
                <a href="/subcategories" class="nav-link">
                    <span class="sidebar-icon"><span class="fa fa-list"></span></span> 
                    Подкатегории
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'users' in segment %} active {% endif %}">
                <a href="/users" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-user"></span></span> 
                    Пользователи бота
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'packages' in segment %} active {% endif %}">
                <a href="/packages" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-box"></span></span> 
                    Пакеты
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'prodInPack' in segment %} active {% endif %}">
                <a href="/productsinpackage" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-box-open"></span></span> 
                    Товары в пакетах
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'drivers' in segment %} active {% endif %}">
                <a href="/drivers" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-car"></span></span> 
                    Водители
                </span>
                </a>
            </li>
            <li class="nav-item  {% if 'routes' in segment %} active {% endif %}">
                <a href="/routes" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-route"></span></span> 
                    Маршруты
                </span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('base_blueprint.logout') }}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-sign-out-alt text-danger"></span></span>
                    <span>Выход</span>
                </a>
            </li>            
            </ul>
        </div>
    </nav>